### PR TITLE
Php8 support

### PR DESCRIPTION
**Pull request by Nielsvanpach**
- Moved from Travis to Github Actions
- Added support for PHP 8.0
- Dropped support for PHP < 7.0

Would be great to see this package support PHP 8!
You can see the tests passed on my fork: https://github.com/Nielsvanpach/reactphp-child-process-promise/actions/runs/400933361

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Awesome thank you! It was already on my list but it's great to see you picked this up already 👍

**Comment by Nielsvanpach** [comment]
You're welcome. Are you planning on releasing this soon?

**Comment by WyriHaximus** [comment]
Yeah within the hour, just need to add a few more workflows and such from other repo's I've been working on upgrading

**Comment by Nielsvanpach** [comment]
Great, thanks. Good luck!

**Comment by WyriHaximus** [comment]
@Nielsvanpach Done: [`3.0.0`](https://github.com/WyriHaximus/reactphp-child-process-promise/releases/tag/3.0.0)

**Pull request merged**
